apiVersion: ENC[AES256_GCM,data:CNI=,iv:7L4gds3HTnAbz07bGUb3gvH6Eh92k8uuS/cnRmJnLko=,tag:HiKjdEtoSyZ76gjxz7RdZg==,type:str]
kind: ENC[AES256_GCM,data:wSIrHH0g,iv:/xdPXH7dVjIBPDcXVkMyM9XofrrSjZhcyrAwB4EK7Bs=,tag:J7BnQEP5LOsc6jgyWXKUSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H+eAIdpaXaIaalQF,iv:8bXKTVM9/cwEPw9KILSsoAH60R8f0GaUOwVAIQxERfA=,tag:nRExaDea1F01l9KyU8AjRQ==,type:str]
    namespace: ENC[AES256_GCM,data:jqunrwjCVg==,iv:JtumTQyy+OyqupyOsWQ2ALRoI83GGFRMu/a+KUrWUzs=,tag:5o7i4naRXm7mn8ITLq4HTg==,type:str]
type: ENC[AES256_GCM,data:8dRYuL2q,iv:Yg23n9iFSMa6AqMZ54By0WkOlaLHsmdygRTz8mfQ6cg=,tag:s+1l6oJiYlsza9NaaNDMwA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:AGBEa/+L,iv:d55j10ae5EgJwKHskwD2vR2AL8L1DxSRQNjp2xdI/vY=,tag:Dl1VIYsLGq8tpT2+Ovj4Og==,type:str]
    password: ENC[AES256_GCM,data:os+C7a6v,iv:mslRKP5nKN+NPpK9mifKo0BFngZzOX82IvTB5NLUSYQ=,tag:E5Cz+rgT8011yVdcJgvh+w==,type:str]
sops:
    age:
        - recipient: age1ggqm0janjs9uepzqvyyk864denfdd9qa7jusajlndt6feqchtf3q35s5d2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMjI4TmR0QjAvc2hFaG5p
            NmpwOXJLWjhzOXdEaUNNNEZjeDI5TlRLV2xNCkYzZm0zcE0ycnhqTFdYYnd1YnFy
            emh1SDUwL3VGREVKY1h2ZVUxMXc5dkkKLS0tIDVPdWtkWXMwYXAwZGFzWExweUVP
            dmV0TE1BdjkrSFZkWnBPbU9YejJJZG8K5Pvd+SDDjBWNmzRNvLip8jbLjnln9u7h
            aYJNmrg8x1KAsmOC1fi+9K4VDRc9BzHl7kV3o/WQC6UV4sYBD+WhtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T09:00:55Z"
    mac: ENC[AES256_GCM,data:w2JheLXEI98/kwrjZBpqPPRxm+aPMCih8Ep2se1beztlzXrlLSObr0QLwoRrYjXFHkkioot6Ol/ik+VokDCdGP21ipfBcBFGoK2jAhPZeQehj6pk95thH7yBYOvJqotqkjfN9ZnlDCi1rgUMfVYQmtxbvCfwLPf2RmWwrs7yo38=,iv:w6fTwVLlpDsNDyjsaQwHJs9qt5G5TPtj008wEuWh5j0=,tag:U0EDGyvJSnP46VQz7Amozw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
