apiVersion: ENC[AES256_GCM,data:31U=,iv:l/4ocXK32igfqyBr6bCZ9PMJi456T7Ov6t/mc1kauN0=,tag:NyAPKbiDgFigkzHv2WbBzA==,type:str]
kind: ENC[AES256_GCM,data:LwCV7N2c,iv:Tr+ssXfHeknwK9mMbYtk8Z4XZi2nYSgtpXJX0tMWMpg=,tag:PW8fVUQ3HajbosX7v2L+dg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2M3vX1+wyJbSmjwI,iv:BaeKObsiiiP+kwpdK2bC9CdemZzRpG5oFAY0GQirj6A=,tag:oP18pGzdFglsZzCdG523Yg==,type:str]
    namespace: ENC[AES256_GCM,data:qFOCyYI3EA==,iv:dPNVFUv8JWCC0ozi/LFwjIXBJPfuR7gCF2aXT2U2pdU=,tag:b5yx0FdO0VTluDolkzRAkQ==,type:str]
type: ENC[AES256_GCM,data:pikNYN7x,iv:9VgTlLtielrN+qiz/att993OILRXlz0ciRRAW8Cz4zk=,tag:NJm23ISG0hEhj7RU1UTWhw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:hDkcIE6l,iv:gdtUO1diyVzkzwnmdThH+AcGWyh2akbUnHIQa5CQzrA=,tag:7PfS5YUwr2fT7G62xF03BA==,type:str]
    password: ENC[AES256_GCM,data:YW/PTBdU,iv:EQkWbwmZRHjBT9mkvvELjGjUd2QZ9iI7IY6m8q6MMZ8=,tag:t7ZzBBZyhYWD6uz6Jro9LA==,type:str]
sops:
    age:
        - recipient: age17nd2u5umaxlxv2vca50kch8yectg6edl8rk5lyuc8md9nswwje8qatcpmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UlJPay8rcjlrZUd1citI
            TnhYdUU0R3FkRlQ2THpERkhQSXZ5K0RhZkVRCnY0ZjM3ME9ackU3dmFjSm1zVUVU
            T1l5TnowbUs0S1hYblUra3AxMjJzZTQKLS0tIE5GNkdkVTIzQ1lnamt6MWVTYVFn
            SkJ5MXk4QXVFT2haNWN0QSsrL2l5ZGMKrbeLdlFf0rU4QukTYk+91JlxSc1GCSlv
            HOzu2QJO7ju46pKZa36fhOiUUjB1uM1ss4dTarku6lAngYb44KUwoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T11:07:10Z"
    mac: ENC[AES256_GCM,data:Uc5SyaUyZ8xALc0D0X0W0H0WPwNZb6rMT+kz3N2vDF6fsLAPkuG7VjEMTyCA9KF5Um9uNXYCKy/xZDD2kwiAdxHMkT3GTwtlh/tJ17APr2B6jE5YpDXdgqYdOFBdD+Lbpxrnoaaceu3lwcgcQQ1gDruAchR5fbXzX8lpLyrPj5A=,iv:ZtCk+ROJAlFHJyTnpSsRqSd6Q27ADPUBjKB3e+5uwW8=,tag:Y7RSk885hjZUTC1SAIGEFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
