apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  # make sure the chart version is pinned to 4.11.7 as requested
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.7"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: LoadBalancer
        # optional: set externalTrafficPolicy to Local if needed
        externalTrafficPolicy: Cluster
      admissionWebhooks:
        enabled: true
